version: "3.9"

services:
  frontend:
    image: ghcr.io/sdaezeu/hms-frontend:latest
    container_name: hms-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: ghcr.io/sdaezeu/hms-backend:latest
    container_name: hms-backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PORT=4000
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=medicarehms
      - BASE_URL=https://hms.ezeu.in
      - UPLOADS_DIR=uploads
      - UPLOADS_URL_PREFIX=/uploads

  db:
    image: postgres:15
    container_name: hms-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      BASE_URL: ${BASE_URL}
      UPLOADS_DIR: ${UPLOADS_DIR}
      UPLOADS_URL_PREFIX: ${UPLOADS_URL_PREFIX}
      
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

volumes:
  db_data:
