version: "3.9"

services:
  frontend:
    image: ghcr.io/2manoj1/hms-frontend:latest
    container_name: hms-frontend
    restart: always
    depends_on:
      - backend

  backend:
    image: ghcr.io/2manoj1/hms-backend:latest
    container_name: hms-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=4000
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=medicarehms

  db:
    image: postgres:15
    container_name: hms-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medicarehms
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: hms-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
